#Read in files, create DDS object using DESeq2
library(tximport)
library(DESeq2)
library(hd5sum)
library(biomaRt)


dir <- ("~/new_Kallisto_Quant/CYTO/")
samples <- read.table(file.path(dir, "meta.cyto.txt"), 
                        sep="\t", header=T, row.names="Sample")
                        
files <- file.path(dir, rownames(samples), "abundance.h5")
names(files) <- paste0(rownames(samples))

mart <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
results <- getBM(attributes = c("ensembl_transcript_id_version", "ensembl_gene_id"), mart = mart)
tx2gene <- results[, 1:2]
txi <- tximport(files, type = "kallisto", tx2gene = tx2gene)

samples$rep <- as.factor(samples$rep)
samples$condition <- as.factor(samples$condition)
dds <- DESeqDataSetFromTximport(txi, colData = samples, design = ~ rep + condition )
dds$condition <- relevel(dds$condition, ref = "PA") 
keep <- rowSums(counts(dds)) >= 32 #remove rows with counts less than 20
dds <- dds[keep,]
dds <- DESeq(dds) 

# Log2 transformation
cts <- counts(dds, normalized=T)
log_counts <- log2(cts + 1)

# rename samples for elaine.
renamed <- c("H88-ARIA_S2-", "H88-ARIA_S2+", "H88-PA",
             "H89-ARIA_S2-", "H89-ARIA_S2+", "H89-PA",
             "H90-ARIA_S2-", "H90-ARIA_S2+", "H90-PA",
             "H91-ARIA_S2-", "H91-ARIA_S2+", "H91-PA")
             
colnames(log_counts) <- renamed
log_counts <- as.data.frame(log_counts)

# sample to sample heatmap
library(gplots)
library(RColorBrewer)
num_conditions <- nlevels(samples$Condition)
pal <- colorRampPalette(brewer.pal(num_conditions, "Set1"))(num_conditions)
cond_colors <- pal[as.integer(samples$condition)]
pdf(file="~/new_Kallisto_Quant/CYTO/cyto_sample_heatmap.pdf",width=9)
heatmap.2(cor(log_counts), RowSideColors=cond_colors, margins=c(10,10), cexCol = 0.2 + 1/log10(16),
          labCol = F, dendrogram = "row", key = F,
          trace='none', main='CYTO Sample correlations (log2-transformed)')
dev.off()

# Pvclust dendogram
library(pvclust)
result <- pvclust(log_counts, method.dist = "cor", method.hclust = "average", nboot = 1000)
pdf(file="~/new_Kallisto_Quant/Control/cyto_sample_hclust.pdf")
plot(result)
pvrect(result)
dev.off()

# PCA
library(PCAtools)
rownames(samples) <- renamed
p <- pca(log_counts, metadata = samples)


# Stacked PCA / Correlation plots
p1 <- biplot(p, x="PC1", y="PC2",
  colby = 'condition', colkey = c('ARIA'='royalblue', 'ARIA_CD362'='forestgreen', "PA"="purple"),
  hline = 0, vline = 0,
  #legendPosition = 'right', legendLabSize = 12, legendIconSize = 8.0,
  drawConnectors = TRUE,
  title = 'Control PCA bi-plot',
  subtitle = 'PC1 versus PC2')

p2 <- biplot(p, x="PC2", y="PC3",
  colby = 'condition', colkey = c('ARIA'='royalblue', 'ARIA_CD362'='forestgreen', "PA"="purple"),
  hline = 0, vline = 0,
  #legendPosition = 'right', legendLabSize = 12, legendIconSize = 8.0,
  drawConnectors = TRUE,
  title = 'Control PCA bi-plot',
  subtitle = 'PC2 versus PC3')

p3 <- biplot(p, x="PC4", y="PC3",
  colby = 'condition', colkey = c('ARIA'='royalblue', 'ARIA_CD362'='forestgreen', "PA"="purple"),
  hline = 0, vline = 0,
  #legendPosition = 'right', legendLabSize = 12, legendIconSize = 8.0,
  drawConnectors = TRUE,
  subtitle = 'PC3 versus PC4')

p4 <- biplot(p, x="PC4", y="PC5",
  colby = 'condition', colkey = c('ARIA'='royalblue', 'ARIA_CD362'='forestgreen', "PA"="purple"),
  hline = 0, vline = 0,
  #legendPosition = 'right', legendLabSize = 12, legendIconSize = 8.0,
  drawConnectors = TRUE,
  subtitle = 'PC4 versus PC5')
p5 <- eigencorplot(p, components = getComponents(p, 1:10), metavars=c('condition', 'rep'))

library(gridExtra)
pdf(file="~/new_Kallisto_Quant/Control/PCA.pdf", width=10, height=12)
grid.arrange(arrangeGrob(p1, p2, p3, p4, ncol=2, nrow=2),
             arrangeGrob(p5 ,ncol = 1, nrow=1), heights=c(4/5, 1/5))
dev.off()


# loadings plot..
pdf(file="~/new_Kallisto_Quant/Control/PCA_loadings.pdf", height=8, width=12)
plotloadings(p,
    components = getComponents(p, c(4,5)),
    rangeRetain = 0.1,
    labSize = 3.0,
    absolute = FALSE,
    title = 'Loadings plot PC4, PC5',
    caption = 'Top 10% variables',
    shape = 23, shapeSizeRange = c(5, 15),
    col = c('limegreen', 'black', 'red3'),
    drawConnectors = TRUE)
    
dev.off()

# DESeq2 RESULTS
res <- results(dds, filterFun=ihw, alpha=0.1, c("condition", "ARIA", "PA"))

# Function for Outputs
```{R}
generate_output <- function(x, prefix){
  up_key <-  intersect(rownames(x)[which(x$log2FoldChange>=1)],
                       rownames(x)[which(x$pvalue<=0.1)])
  
  up_df <- as.data.frame((x)[which(rownames(x) %in% up_key),])
  up_df <- tibble::rownames_to_column(up_df, "ensembl_gene_id")
  
  info <- getBM(attributes=c("ensembl_gene_id",
                        "external_gene_name",
                        "chromosome_name",
                        "start_position",
                        "end_position",
                        "description"),
                        filters = c("ensembl_gene_id"),
                        values = up_df$ensembl_gene_id,
                        mart = mart)
  
  tmp <- merge(info, up_df, by="ensembl_gene_id")
  tmp <- tmp[order(-tmp$log2FoldChange),]
  write.table(tmp, paste0(prefix,"_up_reg.txt"),
              sep="\t", row.names = F, quote=F)
  
  down_key <- intersect(rownames(x)[which(x$log2FoldChange<=-1)],
                        rownames(x)[which(x$pvalue<=0.1)])
  
  down_df <- as.data.frame((x)[which(rownames(x) %in% down_key),])
  down_df <- tibble::rownames_to_column(down_df, "ensembl_gene_id")
  
  info <- getBM(attributes=c("ensembl_gene_id",
                        "external_gene_name",
                        "chromosome_name",
                        "start_position",
                        "end_position",
                        "description"),
                         filters = c("ensembl_gene_id"),
                         values = down_df$ensembl_gene_id,
                         mart = mart)
  
  tmp <- merge(info, down_df, by="ensembl_gene_id")
  tmp <- tmp[order(tmp$log2FoldChange),]
  write.table(tmp, paste0(prefix,"_down_reg.txt"), sep="\t", row.names = F, quote=F)
  
  sig_genes <- c(up_key, down_key)
  write.table(sig_genes, paste0(prefix,"_sig_list.txt"), 
              row.names = F, col.names = F, quote=F)
}
```
# call output
```{R}
generate_output(res, "aria_vs_pa")
```


```{R}
# heatmap
de_gene <- read.table("~/new_Kallisto_Quant/aria_vs_pa_sig_list.txt", sep = "\t", header=F)
#counts <- read.table("~/Results/norm_counts.txt", header=T, sep="\t", row.names = "ensembl_gene_id")
key <- as.character(de_gene[,1])
mat <- as.data.frame((log_counts)[which(rownames(log_counts) %in% key),])
mat <- tibble::rownames_to_column(mat, var="gene_id")
mat <- mat  %>% dplyr::select(-c("H88-ARIA_S2+", "H89-ARIA_S2+", "H90-ARIA_S2+", "H91-ARIA_S2+"))
#mat <- tibble::rownames_to_column(mat, var="gene_id")
info <- getBM(attributes=c("ensembl_gene_id","external_gene_name"),
                        filters = "ensembl_gene_id",
                        values =mat$gene_id,
                        mart = mart)

#rownames(mat) <- make.names(info$external_gene_name, unique=TRUE)
mat$gene_id <- info$external_gene_name

mat <- mat %>% distinct()
rownames(mat) <- make.names(mat$gene_id, unique=T)
mat <- subset(mat, select=-c(1))

# careful with this
mat <- mat[!grepl("AC0", rownames(mat)),]
mat <- mat[!grepl("AC1", rownames(mat)),]
mat <- mat[!grepl("AC2", rownames(mat)),]
mat <- mat[!grepl("AL", rownames(mat)),]

pdf("~/new_Kallisto_Quant/Control/aria_vs_pa_heatmap.pdf",height=18)
pheatmap(mat, color=greenred(75), cluster_rows = T,
         fontsize=4, 
         show_rownames = T, scale = "row")
dev.off()

pdf("~/new_Kallisto_Quant/Control/aria_vs_pa_heatmap_no_names.pdf", height=10)
pheatmap(mat, color=greenred(75), cluster_rows = T,
         show_rownames = F, scale = "row")
dev.off()
```

```{R}
#volcano before remove objects
resOrdered <- as.data.frame(res[order(res$padj),])
pdf(file="~/new_Kallisto_Quant/Control/aria_pa_volcano.pdf")
plot(resOrdered$log2FoldChange, resOrdered$padj, col="black", pch=1, cex=1.1,  main="CYTO treated cells \nARIA_S2+ vs PA Volcano Plot")
fsig <-rownames(subset(resOrdered, log2FoldChange > 1 | log2FoldChange < -1,))
fsig_resOrdered_plot=resOrdered[fsig,]
points(fsig_resOrdered_plot$log2FoldChange, fsig_resOrdered_plot$padj, col="green", pch=19, cex=1.1)
psig <-rownames(subset(resOrdered, pvalue < 0.05))
psig_resOrdered_plot=resOrdered[psig,]
points(psig_resOrdered_plot$log2FoldChange, psig_resOrdered_plot$padj, col="blue", pch=18, cex=0.5)
qsig <-rownames(subset(resOrdered, padj < 0.05))
qsig_resOrdered_plot=resOrdered[qsig,]
points(qsig_resOrdered_plot$log2FoldChange, qsig_resOrdered_plot$padj, col="red", pch=8, cex=0.03)
abline(v=c(1,-1), col="black", lwd=1)
abline(h=0.05, col="red",lwd=1)
legend_text = c("<-1 & >1 Log2-Fold-Change", "p-value<0.1", "Adj-P-Value<0.05")
legend_text2 = c("P-Adj <0.05", "Log2-Fold-Change -1.5 to 1.5")
legend("topleft", legend_text,bty="n",pch = c(19,18,8), col=c("green","blue","red"))
legend("topright", legend_text2, bty = "n", lty=c(1, 1), col=c("red", "black"))
dev.off()
```
# Looks bad, lets remove the 3 outliers. ENSG00000204392, ENSG00000284934, ENSG00000285395
```{r}
resOrdered <- resOrdered[order(resOrdered$log2FoldChange),]
#resOrdered <- resOrdered[-c(1:6), , drop = F]
resOrdered <- tail(resOrdered, -1) # top
resOrdered <- head(resOrdered, -6) # bottom
  pdf(file="~/new_Kallisto_Quant/CYTO/aria_pa_volcano.pdf")
  plot(resOrdered$log2FoldChange, resOrdered$pvalue, col="black", pch=1, cex=1.1,  main="Control cells\nARIA_S2- vs. PA Volcano Plot")
  fsig <-rownames(subset(resOrdered, log2FoldChange > 1 | log2FoldChange < -1,))
  fsig_resOrdered_plot=resOrdered[fsig,]
  points(fsig_resOrdered_plot$log2FoldChange, fsig_resOrdered_plot$pvalue, col="green", pch=19, cex=1.1)
  #psig <-rownames(subset(resOrdered, pvalue < 0.1))
  #psig_resOrdered_plot=resOrdered[psig,]
  #points(psig_resOrdered_plot$log2FoldChange, psig_resOrdered_plot$value, col="blue", pch=18, cex=0.5)
  qsig <-rownames(subset(resOrdered, pvalue < 0.1 | log2FoldChange > 1 & log2FoldChange < -1))
  qsig_resOrdered_plot=resOrdered[qsig,]
  points(qsig_resOrdered_plot$log2FoldChange, qsig_resOrdered_plot$pvalue, col="red", pch=8, cex=0.03)
  abline(v=c(1,-1), col="black", lwd=1.5)
  abline(h=0.1, col="red",lwd=1)
  legend_text = c("Log2 FoldChange\nRange: > 1 to < -1", "Significant genes: Pvalue < 0.1")
  legend_text2 = c("Pvalue <0.1", "Log2-Fold-Change\nRange: -1 to 1")
  legend("topright", legend_text,bty="n",pch = c(19,18,8), col=c("green", "red"))
  legend("topleft", legend_text2, bty = "n", lty=c(1.5, 1.5), col=c("red", "black"))
  dev.off()
```
